import unittest
from pathlib import Path


class FollowFeatureVisibilityTest(unittest.TestCase):
    def test_native_follow_and_automatic_wash_controls_are_visible(self):
        html = (Path(__file__).parents[1] / "web" / "index.html").read_text(
            encoding="utf-8"
        )

        self.assertIn('id="followTab" class="tab hidden"', html)
        self.assertIn('id="calendarTab" class="tab hidden"', html)
        self.assertIn('id="calendarView"', html)
        self.assertIn('/api/follows/calendar?month=', html)
        self.assertIn('id="calendarScope"', html)
        self.assertIn("$('followTab').classList.remove('hidden')", html)
        self.assertIn("我的追更", html)
        self.assertIn('id="followLogTab"', html)
        self.assertIn('id="followLogView"', html)
        self.assertIn(">管理日志</button>", html)
        self.assertIn('id="activityJobsCard"', html)
        self.assertIn('id="activityFailedCard"', html)
        self.assertIn('id="activityWashesCard"', html)
        self.assertIn('id="activityFollowsCard"', html)
        self.assertIn('id="activityCompletedCard"', html)
        self.assertIn('id="taskOverlay"', html)
        self.assertIn('id="taskDialogResetStale"', html)
        self.assertIn("/api/admin/workflow-jobs/reset-stale", html)
        self.assertIn("/api/admin/workflow-jobs/reset-failed", html)
        self.assertIn("重置全部失败任务", html)
        self.assertIn("洗版中", html)
        self.assertIn("refreshMetadata?'?refresh=true':''", html)
        self.assertIn("正在刷新 TMDB…", html)
        self.assertIn("_tmdb_refreshed_at", html)
        self.assertIn("<300000", html)
        self.assertIn("embyProgressCache", html)
        self.assertIn("emby_progress_loading:item.media_type==='tv'", html)
        self.assertIn("episode-progress/${resolved.tmdb_id}?refresh=true", html)
        self.assertIn("正在刷新 Emby…", html)
        self.assertIn("查看完整处理链", html)
        self.assertIn("例行后台检查不会显示在这里", html)
        self.assertNotIn('<option value="poll">后台轮询</option>', html)
        self.assertIn("影巢更新通知", html)
        self.assertIn('id="hdhiveMessageInbox"', html)
        self.assertIn('class="follow-event-poster"', html)
        self.assertIn("hdhiveMessagesLoaded", html)
        self.assertIn("/api/admin/hdhive/messages", html)
        self.assertIn("查看后续处理", html)
        self.assertIn("查看详情", html)
        self.assertIn("detail_fields", html)
        self.assertIn('id="followLogResourceStatus"', html)
        self.assertIn("未完结（追更中）", html)
        self.assertIn("resource_status:currentDetail.media_type", html)
        self.assertIn("/api/admin/hdhive/follow-events", html)
        self.assertIn("站内信检查间隔", html)
        self.assertIn('<option value="1800">每30分钟</option>', html)
        self.assertIn('<option value="3600">每1小时</option>', html)
        self.assertIn('<option value="21600">每6小时</option>', html)
        self.assertIn('<option value="43200">每12小时</option>', html)
        self.assertNotIn('<option value="300">每5分钟</option>', html)
        self.assertNotIn('<option value="900">每15分钟</option>', html)
        self.assertIn("hdhive.poll_interval||3600", html)
        self.assertIn("定时检查影巢站内信", html)
        self.assertIn("停止本集洗版", html)
        self.assertIn("data-follow-stop-wash", html)
        self.assertIn("/wash/${season}/${episode}", html)
        self.assertIn("已经提交给115的转存不会撤回", html)
        self.assertIn('<meta name="google" content="notranslate">', html)
        self.assertIn('<body translate="no">', html)
        self.assertIn("button.textContent='收起时间线'", html)
        self.assertIn("button.textContent='处理时间线';return", html)
        self.assertIn("timeZone:'Asia/Shanghai'", html)
        self.assertIn("115自动洗版窗口", html)
        self.assertNotIn('data-follow-index="${index}"', html)

        self.assertIn('id="detailFollow"', html)
        self.assertIn("item.series_status==='ongoing'", html)
        self.assertIn("slug:resource.slug", html)
        self.assertIn('class="poster-library-status ${item.in_library?', html)
        self.assertIn("item.in_library?'已入库':'未入库'", html)
        self.assertNotIn("showApp();loadSiteNotice();loadRequests();loadFollows()", html)
        self.assertNotIn("手动选择满意版本后，115账号直接转存", html)
        self.assertIn("下一步：开启追更", html)
        self.assertIn("先转存，再追更", html)
        self.assertIn("data-retry-details", html)
        self.assertIn('data-retry-resource="${provider}"', html)
        self.assertIn("loadDetailResource('hdhive'", html)
        self.assertIn("loadDetailResource('guanying'", html)
        self.assertIn("loadDetailResource('dian'", html)
        self.assertIn("refresh?'?refresh=true':''", html)
        self.assertIn("let requestsLoadPromise = null", html)
        self.assertIn("document.visibilityState==='visible'", html)
        self.assertIn("}, 120000);", html)
        self.assertIn("}, 60000);", html)
        self.assertNotIn("}, 15000);", html)
        self.assertIn('loading="lazy" decoding="async"', html)
        self.assertIn("后台独立读取中，不会等待另一个资源源", html)
        self.assertIn("接口速度检测", html)
        self.assertIn("data-test-integration=\"tmdb\"", html)
        self.assertIn('data-view="storage">资源和网盘</button>', html)
        self.assertIn('id="pansaveApiId"', html)
        self.assertIn('id="pansaveApiHash"', html)
        self.assertIn('id="pansavePhone"', html)
        self.assertIn('id="pansaveBotUsername"', html)
        self.assertIn("选择直接发给 Telegram 机器人", html)
        self.assertIn('id="p123DeliveryMode"', html)
        self.assertIn("123 Emby", html)
        self.assertIn('id="settingsEmbyLibraryNotification"', html)
        self.assertIn('id="settingsP123EmbyLibraryNotification"', html)
        self.assertIn('id="settingsEmbyWebhookEnabled"', html)
        self.assertIn('id="settingsP123EmbyWebhookEnabled"', html)
        self.assertIn('id="settingsEmbyWebhookUrl" readonly', html)
        self.assertIn('id="settingsP123EmbyWebhookUrl" readonly', html)
        self.assertIn("emby_library_notification_enabled:$('settingsEmbyLibraryNotification').checked", html)
        self.assertIn("p123_emby_library_notification_enabled:$('settingsP123EmbyLibraryNotification').checked", html)
        self.assertIn("emby_webhook_enabled:$('settingsEmbyWebhookEnabled').checked", html)
        self.assertIn("p123_emby_webhook_enabled:$('settingsP123EmbyWebhookEnabled').checked", html)
        self.assertIn("PanSave", html)
        self.assertIn('id="hdhiveAutoTransfer"', html)
        self.assertIn('id="hdhiveOfflineRetryCleanup"', html)
        self.assertIn('id="hdhiveWashWindow"', html)
        self.assertIn('id="hdhiveMaxTransfers"', html)
        self.assertIn('data-hdhive-filter="${key}"', html)
        self.assertIn("推荐按集数完整度、集数和文件大小排序", html)
        self.assertIn("visible.length-8", html)
        self.assertIn("visible=visible.slice(0,8)", html)
        self.assertIn('data-resource-expand="${provider}"', html)
        self.assertIn("resource-expand-tool", html)
        self.assertIn("resource.actual_unlock_points??resource.unlock_points", html)
        self.assertIn("解锁积分 ${escapeHtml", html)
        self.assertIn("预计消耗：${pointsLabel} 积分", html)
        self.assertIn("↓ 展开其余 ${hiddenCount} 个资源", html)
        self.assertIn("dianResourcesExpanded", html)
        self.assertNotIn("已转存到115所选目录", html)
        self.assertIn('data-storage-panel="overview"', html)
        self.assertIn('data-storage-panel="hdhive"', html)
        self.assertIn('data-storage-panel="guanying"', html)
        self.assertIn('data-storage-panel="wash"', html)
        self.assertIn('id="guanyingCaptchaImage"', html)
        self.assertIn('id="washMagnetFollow"', html)
        self.assertIn('data-wash-group="resolutions"', html)
        self.assertIn('id="washMinScoreGain"><option', html)
        self.assertIn("取消某一维全部选项即关闭该维度", html)
        self.assertIn('/api/admin/wash-rules', html)
        self.assertIn('data-storage-panel="p115"', html)
        self.assertNotIn('class="secret-settings"', html)
        self.assertIn("$('settingsTelegramToken').value=settings.telegram_token||''", html)
        self.assertIn("$('hdhiveAppSecret').value=hdhive.app_secret||''", html)
        self.assertIn("$('dianApiKey').value=settings.dian_api_key||''", html)
        self.assertIn("$('pansaveApiHash').value=settings.pansave_telegram_api_hash||''", html)
        self.assertNotIn('id="settingsTelegramToken" type="password"', html)
        self.assertIn('id="newUserCard" class="panel member-create"', html)
        self.assertIn('id="p123FolderPicker"', html)
        self.assertIn('id="p123StagingPath"', html)
        self.assertNotIn('id="newP123Folder"', html)
        self.assertNotIn('data-user-folder=', html)
        self.assertNotIn('id="p123ClientSecret"', html)
        self.assertIn('data-settings-panel="media"', html)
        self.assertIn('data-settings-panel="telegram"', html)
        self.assertIn('data-settings-panel="wecom"', html)
        self.assertIn('class="settings-layout"', html)
        self.assertIn("const scope='manual'", html)
        self.assertIn("const actionLabel='转存此资源'", html)
        self.assertIn("function formatResourceSize(value)", html)
        self.assertIn("`${Math.round(gigabytes*10)/10} GB`", html)
        self.assertIn("resource.size_label||formatResourceSize(resource.size_gb)", html)
        self.assertIn('class="resource-tag resource-size" title="文件大小"', html)
        self.assertIn('>文件大小 ${escapeHtml(size)}</span>', html)
        self.assertIn('class="resource-tag resource-subtitle"', html)
        self.assertIn("new AbortController()", html)
        self.assertIn("const searchCache = new Map()", html)
        self.assertIn("Boolean(result.refresh_recommended)", html)
        self.assertIn("&refresh=true", html)
        self.assertIn("const merged=[...fresh,...items]", html)
        self.assertNotIn("function normalizeResource(resource,index,item)", html)
        self.assertIn('id="detailRequest"', html)
        self.assertIn("都不满意，提交求片", html)
        self.assertIn("${requestShortcut}</div>", html)
        self.assertNotIn("安全转存缺失集", html)
        self.assertNotIn("115安全预检", html)
        self.assertNotIn("confirm_whole:", html)
        self.assertNotIn("按实际缺集自动安全补齐", html)

    def test_detail_does_not_repeat_p123_robot_delivery_note(self):
        html = (Path(__file__).parents[1] / "web" / "index.html").read_text()
        self.assertNotIn("123目标只发送解锁后的链接", html)

    def test_follow_progress_refreshes_after_initial_list_render(self):
        html = (Path(__file__).parents[1] / "web" / "index.html").read_text()
        self.assertIn("refreshFollowEmbyProgress(follows)", html)
        self.assertIn("api('/api/follows/emby-progress')", html)
        self.assertNotIn("api(`/api/follows/${item.id}/emby-progress`)", html)
        self.assertNotIn("await refreshFollowEmbyProgress(follows)", html)

    def test_admin_can_edit_notice_inline(self):
        html = (Path(__file__).parents[1] / "web" / "index.html").read_text()
        self.assertIn('id="editNoticeButton"', html)
        self.assertIn('id="noticeForm"', html)
        self.assertIn("/api/admin/notice", html)
        self.assertIn("if(noticeEditing)return", html)


if __name__ == "__main__":
    unittest.main()
